## **NAIVE BAYES CLASSIFIER**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\fymatamton\Downloads\datasetss\titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [5]:
df.drop(['PassengerId', 'Name','SibSp', 'Parch', 'Ticket','Cabin', 'Embarked'],axis='columns', inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [6]:
inputs = df.drop('Survived', axis = 'columns')
target = df.Survived

In [14]:
#inputs.Sex = inputs.Sex.map({'male: 1', 'female: 2'})

In [15]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(4)

   female   male
0   False   True
1    True  False
2    True  False
3    True  False

In [16]:
inputs = pd.concat([inputs, dummies], axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

 **dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female**

In [17]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [18]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [19]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [20]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [22]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [23]:
model.fit(X_train,y_train)

GaussianNB()

In [24]:
model.score(X_test,y_test)

0.7835820895522388

In [26]:
X_test[0:10]

     Pclass        Age      Fare  female
326       3  61.000000    6.2375   False
444       3  29.699118    8.1125   False
595       3  36.000000   24.1500   False
689       1  15.000000  211.3375    True
805       3  31.000000    7.7750   False
194       1  44.000000   27.7208    True
102       1  21.000000   77.2875   False
473       2  23.000000   13.7917    True
607       1  27.000000   30.5000   False
542       3  11.000000   31.2750    True

In [27]:
y_test[0:10]

326    0
444    1
595    0
689    1
805    0
194    1
102    0
473    1
607    1
542    0
Name: Survived, dtype: int64